apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /health
spec:
  ingressClassName: nginx
  rules:
    - host: pedidos-veloz.local
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 5000

          - path: /pedidos/health
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 5000

          - path: /pagamentos/health
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 5000

          - path: /estoque/health
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 5000
