name: CI/CD - Pedidos Veloz

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e push Gateway
        run: |
          docker build -t vinialiare/gateway:latest ./gateway
          docker push vinialiare/gateway:latest

      - name: Build e push Pedidos
        run: |
          docker build -t vinialiare/pedidos:latest ./pedidos
          docker push vinialiare/pedidos:latest

      - name: Build e push Pagamentos
        run: |
          docker build -t vinialiare/pagamentos:latest ./pagamentos
          docker push vinialiare/pagamentos:latest

      - name: Build e push Estoque
        run: |
          docker build -t vinialiare/estoque:latest ./estoque
          docker push vinialiare/estoque:latest
